% RN@HMS Queen Elizabeth
% 17/10/18
% Description.
%
% Notes.
%


function [] = exportDhParamsIntoFile(dh_params, j3_scale_factor, save_file_path)

t = datetime('now');
fileID = fopen( strcat(save_file_path,'DH_parameters_recommendation_v2.txt'), 'wt' );
fprintf(fileID, '# DH PARAMETER RECOMMENDATION\n');
fprintf(fileID, '# This file is generated by matlab codes for da Vinci robot intrinsic calibration tool.\n');
fprintf(fileID, strcat('# AT: ', datestr(datetime)) );
fprintf(fileID, '\n');
fprintf(fileID, '# YOU MUST CHANGE THE FILENAME EXTENSION TO .YAML BEFORE YOU USE IT AS A DAVINCI KINEMATICS CONFIG FILE.\n');
fprintf(fileID, '# ---\n');

fprintf(fileID, '# DH_0 TO DH_1 FRAME\n');
fprintf(fileID, 'theta_1: %f \n', dh_params.dh_1.theta);
fprintf(fileID, 'alpha_1: %f \n', dh_params.dh_1.alpha);
fprintf(fileID, 'a_1: %f \n', dh_params.dh_1.a);
fprintf(fileID, 'd_1: %f \n', dh_params.dh_1.d);
fprintf(fileID, '\n');

fprintf(fileID, '# DH_1 TO DH_2 FRAME\n');
fprintf(fileID, 'theta_2: %f \n', dh_params.dh_2.theta);
fprintf(fileID, 'alpha_2: %f \n', dh_params.dh_2.alpha);
fprintf(fileID, 'a_2: %f \n', dh_params.dh_2.a);
fprintf(fileID, 'd_2: %f \n', dh_params.dh_2.d);
fprintf(fileID, '\n');

fprintf(fileID, '# DH_2 TO DH_3 FRAME\n');
fprintf(fileID, 'theta_3: %f \n', dh_params.dh_3.theta);
fprintf(fileID, 'alpha_3: %f \n', dh_params.dh_3.alpha);
fprintf(fileID, 'a_3: %f \n', dh_params.dh_3.a);
fprintf(fileID, 'd_3: %f \n', dh_params.dh_3.d);
fprintf(fileID, '\n');

fprintf(fileID, '# DH_3 TO DH_4 FRAME\n');
fprintf(fileID, 'theta_4: %f \n', dh_params.dh_4.theta);
fprintf(fileID, 'alpha_4: %f \n', dh_params.dh_4.alpha);
fprintf(fileID, 'a_4: %f \n', dh_params.dh_4.a);
fprintf(fileID, 'd_4: %f \n', dh_params.dh_4.d);
fprintf(fileID, '\n');

fprintf(fileID, '# DH_4 TO DH_5 FRAME\n');
fprintf(fileID, 'theta_5: %f \n', dh_params.dh_5.theta);
fprintf(fileID, 'alpha_5: %f \n', dh_params.dh_5.alpha);
fprintf(fileID, 'a_5: %f \n', dh_params.dh_5.a);
fprintf(fileID, 'd_5: %f \n', dh_params.dh_5.d);
fprintf(fileID, '\n');

fprintf(fileID, 'j3_scale_factor: %f \n', j3_scale_factor);
fprintf(fileID, '\n');
fprintf(fileID, '# Please entre the j1 and j2 scale factor manually for the time being.');
fprintf(fileID, '\n');


fclose(fileID);




end