% RN@HMS Prince of Wales
% 23/07/18
% Description.
%
% Notes.
%

%%
clc
close all
clear all


%% Initialisation

% Get the PSM1 to PSM2 (PSM2 in PSM1 frame) Transform.

data_folder = 'Data/20181105_02/';

load(strcat(data_folder,'affine_psm2_wrt_psm1.mat'))
load(strcat(data_folder,'affine_psm1_wrt_polaris.mat'))
load(strcat(data_folder,'affine_psm2_wrt_polaris.mat'))

affine_psm1_wrt_psm2 = inv(affine_psm2_wrt_psm1);

% Get the PSM1 docking pose

pt_wrt_psm1 = affine_psm2_wrt_psm1(1:3,4);
pt_wrt_psm1 = pt_wrt_psm1/2;
pt_wrt_psm1(4,1) = 1;

pt_wrt_polaris = affine_psm1_wrt_polaris*pt_wrt_psm1;
pt_wrt_polaris = pt_wrt_polaris + [0;0;0.1;0];

pt_y_plus_wrt_polaris = pt_wrt_polaris + [0;0.01;0;0];

pt_wrt_psm1 = inv(affine_psm1_wrt_polaris)*pt_wrt_polaris;
pt_wrt_psm2 = inv(affine_psm2_wrt_polaris)*pt_wrt_polaris;

pt_y_plus_wrt_psm2 = inv(affine_psm2_wrt_polaris)*pt_y_plus_wrt_polaris;


% PSM1 orientation
psm1_tip_rot_wrt_polaris = [-1 0 0;
    0 0 1;
    0 1 0];

psm2_tip_rot_wrt_polaris = [1 0 0;
    0 0 -1;
    0 -1 0];

affine_psm1_tip_wrt_polaris(1:3, 1:3) = psm1_tip_rot_wrt_polaris;
affine_psm1_tip_wrt_polaris(1:3, 4) =  pt_wrt_polaris(1:3,1);
affine_psm1_tip_wrt_polaris(4, 1:4) = [0 0 0 1];

affine_psm2_tip_wrt_polaris(1:3, 1:3) = psm2_tip_rot_wrt_polaris;
affine_psm2_tip_wrt_polaris(1:3, 4) =  pt_wrt_polaris(1:3,1);
affine_psm2_tip_wrt_polaris(4, 1:4) = [0 0 0 1];

affine_psm2_tip_y_plus_wrt_polaris(1:3, 1:3) = psm2_tip_rot_wrt_polaris;
affine_psm2_tip_y_plus_wrt_polaris(1:3, 4) =  pt_y_plus_wrt_psm2(1:3,1);
affine_psm2_tip_y_plus_wrt_polaris(4, 1:4) = [0 0 0 1];

affine_psm1_tip_wrt_base = inv(affine_psm1_wrt_polaris)*affine_psm1_tip_wrt_polaris;
affine_psm2_tip_wrt_base = inv(affine_psm2_wrt_polaris)*affine_psm2_tip_wrt_polaris;
affine_psm2_tip_y_plus_wrt_base = inv(affine_psm2_wrt_polaris)*affine_psm2_tip_y_plus_wrt_polaris;


%%
     % PSM1 go to stand still point and PSM2 go to prepose
     disp(strcat(num2str(affine_psm1_tip_wrt_base(1,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,3)), ',  ',...
         num2str(-1), ',  ', ...
         num2str(affine_psm2_tip_y_plus_wrt_base(1,4)), ', ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(2,4)), ', ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(3,4)), ', ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(1,1)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(2,1)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(3,1)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(1,3)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(2,3)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(3,3)), ',  ',...
         num2str(0.8), ',  ', ...
         num2str(10))); 
     
     % Stay there
     disp(strcat(num2str(affine_psm1_tip_wrt_base(1,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,3)), ',  ',...
         num2str(-1), ',  ', ...
         num2str(affine_psm2_tip_y_plus_wrt_base(1,4)), ', ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(2,4)), ', ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(3,4)), ', ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(1,1)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(2,1)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(3,1)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(1,3)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(2,3)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(3,3)), ',  ',...
         num2str(0.8), ',  ', ...
         num2str(15)));      
   
     % Approach
     disp(strcat(num2str(affine_psm1_tip_wrt_base(1,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,3)), ',  ',...
         num2str(-1), ',  ', ...
         num2str(affine_psm2_tip_wrt_base(1,4)), ', ',...
         num2str(affine_psm2_tip_wrt_base(2,4)), ', ',...
         num2str(affine_psm2_tip_wrt_base(3,4)), ', ',...
         num2str(affine_psm2_tip_wrt_base(1,1)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(2,1)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(3,1)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(1,3)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(2,3)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(3,3)), ',  ',...
         num2str(0.8), ',  ', ...
         num2str(20)));  
     
     % Stay there
     disp(strcat(num2str(affine_psm1_tip_wrt_base(1,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,3)), ',  ',...
         num2str(-1), ',  ', ...
         num2str(affine_psm2_tip_wrt_base(1,4)), ', ',...
         num2str(affine_psm2_tip_wrt_base(2,4)), ', ',...
         num2str(affine_psm2_tip_wrt_base(3,4)), ', ',...
         num2str(affine_psm2_tip_wrt_base(1,1)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(2,1)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(3,1)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(1,3)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(2,3)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(3,3)), ',  ',...
         num2str(0.8), ',  ', ...
         num2str(23))); 
     
     % Pinch
     disp(strcat(num2str(affine_psm1_tip_wrt_base(1,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,3)), ',  ',...
         num2str(0), ',  ', ...
         num2str(affine_psm2_tip_wrt_base(1,4)), ', ',...
         num2str(affine_psm2_tip_wrt_base(2,4)), ', ',...
         num2str(affine_psm2_tip_wrt_base(3,4)), ', ',...
         num2str(affine_psm2_tip_wrt_base(1,1)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(2,1)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(3,1)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(1,3)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(2,3)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(3,3)), ',  ',...
         num2str(-1), ',  ', ...
         num2str(27)));      
     
     % PSM1 open
     disp(strcat(num2str(affine_psm1_tip_wrt_base(1,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,3)), ',  ',...
         num2str(1), ',  ', ...
         num2str(affine_psm2_tip_wrt_base(1,4)), ', ',...
         num2str(affine_psm2_tip_wrt_base(2,4)), ', ',...
         num2str(affine_psm2_tip_wrt_base(3,4)), ', ',...
         num2str(affine_psm2_tip_wrt_base(1,1)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(2,1)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(3,1)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(1,3)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(2,3)), ',  ',...
         num2str(affine_psm2_tip_wrt_base(3,3)), ',  ',...
         num2str(-1), ',  ', ...
         num2str(30)));        
     
     % PSM2 retreats
     disp(strcat(num2str(affine_psm1_tip_wrt_base(1,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,4)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,1)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(1,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(2,3)), ',  ',...
         num2str(affine_psm1_tip_wrt_base(3,3)), ',  ',...
         num2str(-1), ',  ', ...
         num2str(affine_psm2_tip_y_plus_wrt_base(1,4)), ', ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(2,4)), ', ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(3,4)), ', ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(1,1)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(2,1)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(3,1)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(1,3)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(2,3)), ',  ',...
         num2str(affine_psm2_tip_y_plus_wrt_base(3,3)), ',  ',...
         num2str(-1), ',  ', ...
         num2str(35)));      
     
     
     
     
     
     
     
     



